---
- name: Checking if thefuck is installed
  shell: pip3 list | grep thefuck
  register: thefuck_installed
  changed_when: false
  failed_when: false

- name: Installing thefuck
  pip:
    name: thefuck
    executable: pip3
    extra_args: --user
  when: thefuck_installed.rc != 0

- name: Installing gti
  npm:
    name: gti
    global: yes
  when: npm_global_packages.stdout is not search('gti')